# Site settings
title: Personal Blog
subtitle: copy by jekyll
email: zhmi1204@gmail.com & zhmi1204@163.com
description: My first copy site
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Becstreet
city: Beijing
state: BJ
zip_code: 10
country: People's Republic of China
phone: 13011152017

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/zhmi1204
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown
